const db = require('../database');

module.exports = {
  getAll: async () => {
    // For PostgreSQL, use STRING_AGG with text cast for UUID; for SQLite, use GROUP_CONCAT
    let query;
    if (db._isPostgres) {
      query = `
        SELECT v.*, STRING_AGG(vl.userId::text, ',') as likes
        FROM vinyls v
        LEFT JOIN vinyl_likes vl ON v.id = vl.vinylId
        GROUP BY v.id
        ORDER BY v.created_at DESC
      `;
    } else {
      query = `
        SELECT v.*, GROUP_CONCAT(vl.userId) as likes
        FROM vinyls v
        LEFT JOIN vinyl_likes vl ON v.id = vl.vinylId
        GROUP BY v.id
      `;
    }
    
    const stmt = db.prepare(query);
    const vinyls = await stmt.all();
    
    return (vinyls || []).map(vinyl => ({
      ...vinyl,
      likes: vinyl.likes ? vinyl.likes.split(',') : []
    }));
  },
  
  getById: async (id) => {
    // For PostgreSQL, use STRING_AGG with text cast for UUID; for SQLite, use GROUP_CONCAT
    let query;
    if (db._isPostgres) {
      query = `
        SELECT v.*, STRING_AGG(vl.userId::text, ',') as likes
        FROM vinyls v
        LEFT JOIN vinyl_likes vl ON v.id = vl.vinylId
        WHERE v.id = $1
        GROUP BY v.id
      `;
    } else {
      query = `
        SELECT v.*, GROUP_CONCAT(vl.userId) as likes
        FROM vinyls v
        LEFT JOIN vinyl_likes vl ON v.id = vl.vinylId
        WHERE v.id = ?
        GROUP BY v.id
      `;
    }
    
    const stmt = db.prepare(query);
    const vinyl = await stmt.get(id);
    
    if (!vinyl) return null;
    
    return {
      ...vinyl,
      likes: vinyl.likes ? vinyl.likes.split(',') : []
    };
  },
  
  create: async (data) => {
    // UUID will be auto-generated by database
    const { title, artist, year, coverUrl, musicUrl, note, ownerId, genre = 'other' } = data;
    
    const query = db._isPostgres
      ? `INSERT INTO vinyls (title, artist, year, coverUrl, musicUrl, note, genre, ownerId)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
         RETURNING id, title, artist, year, coverUrl, musicUrl, note, genre, ownerId, created_at, updated_at`
      : `INSERT INTO vinyls (title, artist, year, coverUrl, musicUrl, note, genre, ownerId)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`;
    
    const stmt = db.prepare(query);
    const result = await stmt.get(title, artist, year, coverUrl || null, musicUrl || null, note || null, genre || 'other', ownerId);
    
    if (!result) return null;
    
    // Format likes array
    return {
      ...result,
      likes: []
    };
  },
  
  update: async (id, data) => {
    const vinyl = await module.exports.getById(id);
    if (!vinyl) return null;
    
    const { title, artist, year, coverUrl, musicUrl, note } = data;
    
    const query = db._isPostgres
      ? `UPDATE vinyls 
         SET title = COALESCE($1, title),
             artist = COALESCE($2, artist),
             year = COALESCE($3, year),
             coverUrl = COALESCE($4, coverUrl),
             musicUrl = COALESCE($5, musicUrl),
             note = COALESCE($6, note),
             updated_at = CURRENT_TIMESTAMP
         WHERE id = $7`
      : `UPDATE vinyls 
         SET title = COALESCE(?, title),
             artist = COALESCE(?, artist),
             year = COALESCE(?, year),
             coverUrl = COALESCE(?, coverUrl),
             musicUrl = COALESCE(?, musicUrl),
             note = COALESCE(?, note)
         WHERE id = ?`;
    
    const stmt = db.prepare(query);
    await stmt.run(title, artist, year, coverUrl, musicUrl, note, id);
    
    return await module.exports.getById(id);
  },
  
  delete: async (id) => {
    const query = db._isPostgres
      ? 'DELETE FROM vinyls WHERE id = $1'
      : 'DELETE FROM vinyls WHERE id = ?';
    
    const stmt = db.prepare(query);
    const result = await stmt.run(id);
    return result.changes > 0;
  },
  
  addLike: async (vinylId, userId) => {
    try {
      const query = db._isPostgres
        ? 'INSERT INTO vinyl_likes (vinylId, userId) VALUES ($1, $2) ON CONFLICT DO NOTHING'
        : 'INSERT OR IGNORE INTO vinyl_likes (vinylId, userId) VALUES (?, ?)';
      
      const stmt = db.prepare(query);
      await stmt.run(vinylId, userId);
      return await module.exports.getById(vinylId);
    } catch (e) {
      console.error('Error adding like:', e.message);
      return null;
    }
  },
  
  removeLike: async (vinylId, userId) => {
    const query = db._isPostgres
      ? 'DELETE FROM vinyl_likes WHERE vinylId = $1 AND userId = $2'
      : 'DELETE FROM vinyl_likes WHERE vinylId = ? AND userId = ?';
    
    const stmt = db.prepare(query);
    const result = await stmt.run(vinylId, userId);
    if (result.changes > 0) {
      return await module.exports.getById(vinylId);
    }
    return null;
  }
};
